import type { Metadata } from 'next';
import './globals.css';
import { Lato, Playfair_Display } from 'next/font/google';
import Nav from '@/components/ui/nav';

export const lato = Lato({
  subsets: [ 'latin' ],
  weight: [ '100', '300', '400', '700', '900' ],
  variable: '--font-lato'
});

export const playfair = Playfair_Display({
  subsets: [ 'latin' ],
  weight: [ '400', '500', '600', '700', '800', '900' ],
  variable: '--font-playfair'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${playfair.variable} antialiased bg-neutral-100`}
      >
        <div className="relative flex h-dvh w-full flex-col">
          <div className="gradient-01 absolute inset-x-1/2 inset-y-0 z-0 h-24 w-[50%]" />
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
